default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:development, :database) %>
  username: <%= Rails.application.credentials.dig(:development, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :password) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:test, :database) %>
  username: <%= Rails.application.credentials.dig(:test, :username) %>
  password: <%= Rails.application.credentials.dig(:test, :password) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production, :database) %>
  username: <%= Rails.application.credentials.dig(:production, :username) %>
  password: <%= Rails.application.credentials.dig(:production, :password) %>
